In [1]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
# Importing the dataset
data = pd.read_csv('data.csv')

# Removing the year
data = data.drop('Year', axis='columns')

In [4]:
data.head()

Purchases (GWh)  losses %  GDP per Capita  Customers  Informal sector (%)  \
0             4319     27.23      548.258047     932598              9.87344   
1             4530     26.47      570.639605    1022847             11.00198   
2             4709     26.42      646.038719    1109357              8.71163   
3             4922     26.33      780.267565    1245935              3.04414   
4             5291     27.01      885.637507    1400258             17.07084   

   price (cedi)  price ($)  Installed Capacity (MW)  reserve margin (MW)  \
0         0.017      0.024                     1652           254.853658   
1         0.034      0.047                     1652           261.219512   
2         0.065      0.077                     1652           269.341463   
3         0.071      0.080                     1652           249.146342   
4         0.074      0.082                     1730           230.268293   

   Suppressed demand  
0               6889  
1               7128  
2               6773  
3               5187  
4               5299

In [5]:
# Splitting ghe data into independent and dependent variables
X = data.iloc[:, :-1].values
y = data.iloc[:, 9].values

# Splitting the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [6]:
X_test

array([[8.65900000e+03, 2.32500000e+01, 1.79660108e+03, 4.07805500e+06,
        2.88045700e+01, 5.41000000e-01, 1.47000000e-01, 3.65600000e+03,
        4.24317073e+02],
       [7.40600000e+03, 2.88800000e+01, 1.71864704e+03, 2.46277100e+06,
        2.60412000e+01, 2.11000000e-01, 1.45000000e-01, 2.16500000e+03,
        3.30585366e+02],
       [4.92200000e+03, 2.63300000e+01, 7.80267565e+02, 1.24593500e+06,
        3.04414000e+00, 7.10000000e-02, 8.00000000e-02, 1.65200000e+03,
        2.49146342e+02],
       [1.23790000e+04, 2.47300000e+01, 2.26011345e+03, 4.39594500e+06,
        3.89521800e+01, 7.05000000e-01, 1.54000000e-01, 4.88900000e+03,
        5.54268293e+02],
       [1.11650000e+04, 2.28000000e+01, 2.07417544e+03, 4.11666200e+06,
        4.72858900e+01, 7.98000000e-01, 1.83000000e-01, 4.38800000e+03,
        4.81170732e+02],
       [9.36800000e+03, 2.50500000e+01, 2.01006151e+03, 3.57172700e+06,
        1.63547700e+01, 4.64000000e-01, 1.45000000e-01, 2.83100000e+03,
        4.3

In [7]:
y_train

array([12528,  5299,  6773,  7224,  6270,  7128, 10583,  6889, 16531,
       15232,  7454,  7219,  9258,  9187,  5932], dtype=int64)

In [8]:
# Scaling the dataset
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_test.shape

(6, 9)

In [10]:
X_train.shape

(15, 9)

In [11]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1)
])

In [12]:
model.compile(loss='mean_absolute_error',
              optimizer=tf.keras.optimizers.Adam(0.001),
             metrics=['accuracy'])

In [13]:
model.fit(X_train, y_train, epochs=1)

1/1 [==============================] - 1s 646ms/step - loss: 8900.9893 - accuracy: 0.0000e+00


In [14]:
model.evaluate(X_test, y_test)

1/1 [==============================] - 0s 202ms/step - loss: 10377.2881 - accuracy: 0.0000e+00


[10377.2880859375, 0.0]

In [15]:
model.predict(X_test)

1/1 [==============================] - 0s 88ms/step


array([[-0.44879264],
       [-0.42240682],
       [-0.7233662 ],
       [-0.41001546],
       [-0.53524435],
       [-0.18602668]], dtype=float32)

In [16]:
y_test

array([10625,  8317,  5187, 14401, 13036, 10695], dtype=int64)